/**
 * Gallery data. Add an item here and the wave picks it up — no other changes.
 * Descriptions are Rayudu Group's own, from the brands deck.
 */
export const BRANDS = [
  { id:'ronohub', title:'Ronohub', category:'Business intelligence', image:'assets/brands/Ronohub.webp',
    description:'Advanced business intelligence platforms, enabling organisations to gather, analyse and transform large volumes of unstructured and structured data — powering informed decision-making and risk assessment across diverse industries.',
    meta:['Decision architecture','Risk assessment','Analytics'] },
  { id:'ogin', title:'Ogin Logistics', category:'Supply chain & logistics', image:'assets/brands/OGIN-Logistics.webp',
    description:'A trusted partner for logistics and supply chain solutions, with comprehensive services to navigate the complexities of modern logistics and keep operations running smoothly.',
    meta:['Multimodal freight','Container management','For the fast moving world…'] },
  { id:'crontle', title:'Crontle', category:'Technology & software', image:'assets/brands/Crontle.webp',
    description:'A leading IT company delivering expert IT services and innovative software development solutions, tailored to the evolving needs of modern businesses.',
    meta:['Enterprise software','Digital architecture','Make the leap'] },
  { id:'blacore', title:'Blacore', category:'Energy & commodities', image:'assets/brands/blacore.webp',
    description:'Coal import and trading across India, supplying various types of coal from all major ports to meet diverse industrial needs.',
    meta:['Coal import & trading','All major Indian ports'] },
  { id:'oneflag', title:'One Flag Entertainment', category:'Film, music & IP', image:'assets/brands/OneFlag.webp',
    description:'Specialising in film, music and digital content, with full-scale production and distribution services — bringing creative visions to life and delivering them to audiences worldwide.',
    meta:['Production','Distribution','Film financing'] },
  { id:'dazzlon', title:'Dazzlon', category:'Consumer wellness', image:'assets/brands/Dazzlon.webp',
    description:'A unique blend of natural and scientifically crafted skincare solutions, designed to nourish and revitalise your skin while promoting a luxurious self-care experience.',
    meta:['Skincare','Personal care'] },
  { id:'natical', title:'Natical Exim', category:'Global trade', image:'assets/brands/NATICALEXIMS.webp',
    description:'An export–import brand connecting businesses across countries through reliable and efficient international trade solutions, facilitating the seamless movement of products across global markets.',
    meta:['Export & import','Local roots to global shoots'] },
  { id:'farms', title:'Rayudu Farms', category:'Agriculture & heritage', image:'assets/brands/Rayudu-Farms.webp',
    description:'Rayudu Farms represents our traditional agricultural roots and farming heritage. It is not a commercial business, but a reflection of our connection to agriculture and our traditional culture.',
    meta:['Traditional farming','Heritage'] },
  { id:'zutopay', title:'ZutoPay', category:'Fintech', image:'assets/brands/ZutoPay.webp',
    description:'A fintech platform focused on payment gateway, BBPS and digital payment solutions — built to offer convenient services across bill payments, ticket bookings and other digital transactions.',
    meta:['Payment gateway','BBPS','Upcoming'] },
  { id:'till24', title:'Till 24', category:'Café & bistro', image:'assets/brands/Till-24.webp',
    description:'A contemporary café and bistro brand offering a welcoming space for quality food, refreshing beverages and memorable dining experiences.',
    meta:['Café','Bistro'] },
  { id:'feyo', title:'Feyo', category:'Financial services', image:'assets/brands/Feyo.webp',
    description:'A financial services brand focused on banking and digital financial solutions, designed to provide simple, accessible and convenient experiences for modern customers.',
    meta:['Banking','Digital finance','Upcoming'] },
  { id:'goodcap', title:'GoodCap', category:'Insurance', image:'assets/brands/Goodcap.webp',
    description:'An insurance-focused brand offering solutions across health insurance and various insurance services, designed to provide protection, security and peace of mind.',
    meta:['Health insurance','Protection'] },
  { id:'halberd', title:'Halberd', category:'Distribution', image:'assets/brands/Halberd.webp',
    description:'A distribution brand connecting beverages and consumer products with markets through reliable and efficient distribution networks.',
    meta:['Beverages','Consumer products'] },
  { id:'araanta', title:'Araanta', category:'Hospitality', image:'assets/brands/Araanta.webp',
    description:'A premium hospitality brand offering hotel and resort booking services, connecting travellers with exceptional stays and memorable experiences.',
    meta:['Hotels','Resorts'] },
  { id:'keento', title:'Keento', category:'AI technology', image:'assets/brands/keento.webp',
    description:'An AI technology brand focused on developing innovative AI-powered tools and intelligent solutions for the future.',
    meta:['AI tools','Upcoming'] }
];
